import { GoogleGenAI } from "@google/genai";
import { ShirtConfig } from "../types";

export const generateTryOn = async (
  imageBase64: string, 
  gender: 'male' | 'female',
  config: ShirtConfig
): Promise<string> => {
  // CRITICAL: Instantiate Client inside the function to capture the latest API Key
  // selected by the user via window.aistudio.
  const apiKey = process.env.API_KEY || '';
  if (!apiKey) {
    throw new Error("API Key is missing. Please select a key.");
  }
  const ai = new GoogleGenAI({ apiKey });

  try {
    const { type, buttonColor, tippingLines, enableChestStripe, accentColor } = config;
    
    const garmentName = type === 'polo' ? "Polo Shirt" : "Crew Neck T-shirt";
    
    // Explicit details for better generation
    let garmentDetail = "";
    if (type === 'polo') {
      garmentDetail = `Ensure the collar is structured with a button placket. The buttons are ${buttonColor}.`;
    } else {
      garmentDetail = "Ensure it has a round crew neckline.";
    }

    // Add accent details to prompt - MADE STRONGER
    let accentDetail = "";
    if (tippingLines > 0) {
      const countText = tippingLines === 1 ? "EXACTLY ONE (Single)" : tippingLines === 2 ? "EXACTLY TWO (Double)" : "EXACTLY THREE (Triple)";
      accentDetail += ` VISUAL PRIORITY: The collar edges and sleeve cuffs have ${countText} distinct ${accentColor} tipping stripes. You MUST render exactly ${tippingLines} line(s) as seen in the source image.`;
    } else {
      accentDetail += " The collar and cuffs are solid colors with NO stripes.";
    }

    if (enableChestStripe) {
      accentDetail += ` There is a prominent ${accentColor} horizontal stripe running across the chest.`;
    }

    const fitInstruction = gender === 'female' 
      ? "IMPORTANT: The garment is a STANDARD LENGTH UNISEX T-SHIRT. It is NOT a dress, tunic, or blouse. The hemline MUST end clearly at the hips/belt line. The fit is 'Regular & Comfortable'. CRITICAL: You must preserve the specific collar construction and STRIPING DETAILS from the input image."
      : "The fit is a MODERN COMFORTABLE FIT (Regular Fit). The length is standard, ending at the hip/belt line, NOT long-line or oversized.";

    const prompt = `
      Create a high-end, photorealistic 3D-style fashion studio photography of a ${gender} model wearing this specific ${garmentName}.
      
      Key Requirements:
      1. THE SHIRT: **It is a ${type.toUpperCase()}**. ${garmentDetail} 
         ${accentDetail}
         ${fitInstruction}
         
         STRICT VISUAL ADHERENCE:
         - Match the input image design EXACTLY.
         - If the input shows stripes on the collar, you MUST render them.
         - If the input shows a logo, place it exactly as shown.
         - The fabric should look premium, like high-quality cotton or pique mesh.
      
      2. THE MODEL: Professional ${gender} fashion model, confident pose, facing forward. 
         Skin texture should be hyper-realistic. 
      
      3. ENVIRONMENT: Clean, modern studio background (soft grey or white). 
         Cinematic lighting setup (rim lighting, soft fill) to enhance the 3D form of the shirt.
      
      Output should look like a professional e-commerce product shot from a luxury brand.
    `;

    // Using Gemini 3 Pro (Nano Banana Pro)
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png',
              data: imageBase64
            }
          },
          {
            text: prompt
          }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: '3:4', // Standard portrait for fashion
          imageSize: '1K'
        }
      }
    });

    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
           return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by the AI.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};