import { GoogleGenAI } from "@google/genai";
import { ShirtConfig } from "../types";

const apiKey = process.env.API_KEY || '';

const ai = new GoogleGenAI({ apiKey });

export const generateTryOn = async (
  imageBase64: string, 
  gender: 'male' | 'female',
  config: ShirtConfig
): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is missing.");
  }

  try {
    const { type, buttonColor, tippingLines, enableChestStripe, accentColor } = config;
    
    const garmentName = type === 'polo' ? "Polo Shirt" : "Crew Neck T-shirt";
    
    // Explicit details for better generation
    let garmentDetail = "";
    if (type === 'polo') {
      garmentDetail = `Ensure the collar is structured. The buttons on the placket must be ${buttonColor} in color.`;
    } else {
      garmentDetail = "Ensure it has a round crew neckline.";
    }

    // Add accent details to prompt
    let accentDetail = "";
    if (tippingLines > 0) {
      const countText = tippingLines === 1 ? "single" : tippingLines === 2 ? "double" : "triple";
      accentDetail += ` The shirt features distinct ${countText} ${accentColor} tipping stripes on the collar edges and sleeve cuffs.`;
    }
    if (enableChestStripe) {
      accentDetail += ` There is a prominent ${accentColor} horizontal stripe running across the chest.`;
    }

    // Specific instruction to fix the "ladies shirt" bug
    // We explicitly tell the AI to use the standard/unisex cut even for females.
    const fitInstruction = gender === 'female' 
      ? "IMPORTANT: The model is wearing a STANDARD FIT UNISEX shirt. Do NOT generate a dress, crop top, or blouse. The hem must end at the hips. Keep the sleeves standard length. It must look exactly like the mens version but on a female model."
      : "The fit should be a standard tailored fit.";

    const prompt = `
      Create a high-end, photorealistic 3D-style fashion studio photography of a ${gender} model wearing this specific ${garmentName}.
      
      Key Requirements:
      1. THE SHIRT: **It is a ${type.toUpperCase()}**. ${garmentDetail} ${accentDetail}
         ${fitInstruction}
         Must perfectly match the input design colors and logos provided in the image. 
         The fabric should look premium, like high-quality cotton or pique mesh.
         Show realistic folds, lighting, and texture.
      
      2. THE MODEL: Professional ${gender} fashion model, confident pose, facing forward. 
         Skin texture should be hyper-realistic. 
      
      3. ENVIRONMENT: Clean, modern studio background (soft grey or white). 
         Cinematic lighting setup (rim lighting, soft fill) to enhance the 3D form of the shirt.
      
      Output should look like a professional e-commerce product shot from a luxury brand.
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png',
              data: imageBase64
            }
          },
          {
            text: prompt
          }
        ]
      }
    });

    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
           return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by the AI.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};